### ISSUE TITLE
No info about licenses and royalties

### ISSUE THREAD

**Issue by rgommers** [pydata/pydata-cookbook#9]
It would be good to add to the README the following:

Q: There are normally royalties for book authors. What happens to those?

A: All royalties go to NumFOCUS and will be used to support the further development of projects in the PyData stack.

Q: Is all content we contribute reusable for documentation of projects?

A: ?

**Comment by aterrel** [comment]
I have confirmation from pearson that we can use chapters for documentation of projects. They would prefer that we don't make them all available in this way so there is some value to buying the book.

**Comment by rgommers** [comment]
Thanks Andy.

> They would prefer that we don't make them all available in this way so there is some value to buying the book.

That makes sense. The SciPy chapter (assuming we'll get around to finishing it any time soon ....) is not really user doc material, so that'll be in the book only very likely.
